[package]
name = "instant_monitor"
version = "v0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.0"
serde = { version = "1.0", features = ["derive"] }
chrono = { version = "0.4", features = ["serde"] }
sysinfo = "0.29"
env_logger = "0.10"
log = "0.4"
if-addrs = "0.10"
mac_address = "1.1"
